### ISSUE TITLE
request in :log instead?

### ISSUE THREAD

**Issue by ccfontes** [yogthos/noir-exception#4]
> Alternatively, it's possible to supply the :error-response-handler key that points to a function which should accept the request as a paremeter and return a string response that will be returned to the client. This can be useful for generating contextual errors based on the contents of the request.

This is awesome, but one would rather `:log` the `request` than send it to the client. What do you think?

Use case
-
When an error occurs in the production environment, an email is sent  to the site admin with the `error` and `request`.

A function in `:log` could do that.

**Comment by yogthos** [comment]
There's no reason the handler couldn't log the request or email it though. The whole idea behind using a handler function is that the library doesn't make any assumptions regarding how the error is handled.

**Comment by ccfontes** [comment]
You're right. :+1:  I'm closing this. Just going to correct some typos in the README btw :)

**Comment by yogthos** [comment]
sounds like a plan and the readme could be updated to be more clear on this sort of thing :)

**Comment by ccfontes** [comment]
If both the `request` and the `error` need to be sent by email, the current implementation only allows it by sending two emails: one in `:log`, and the other in `:error-response-handler`. I think this a problem.

**Comment by yogthos** [comment]
Only one of the handlers should ever be called in any individual request though. So, if you define a function that can handle this functionality then you can call it in both cases, e.g:

```clojure
(defn log [request status]
   (condp = status
      :error (do error stuff)
      :success (do success stuff)
      :else (do something else)))
````

Am I missing anything here?

**Comment by ccfontes** [comment]
From [wrap-internal-error](https://github.com/yogthos/noir-exception/blob/master/src/noir_exception/core.clj#L119-128) fn, I see that both `:log` and `:error-response-handler` <em>can</em> be used at the same time. You advise that one <em>shouldn't</em> though. I don't understand why yet, but maybe it's better to enforce that in the code.

Still, the problem is that `:log` only accepts the `error` input param, while `:error-response-handler` accepts only the `request` input param, according to your readme. But I want to access both input params (`error`, `request`) in the same handler (any handler would do for me) to solve the problem of sending an email with both the `error` and `request`.

I'm sorry if I'm the one missing something here :)

Drop me a line, and I will do a PR for that.

**Comment by yogthos** [comment]
Ok I think I see the use case now. If you'd like to do a PR for it that would be great as you clearly have a specific use case in mind. :)

**Comment by ccfontes** [comment]
OK, I'm on it :)
