### ISSUE TITLE
cause not in error page

### ISSUE THREAD

**Issue by ccfontes** [yogthos/noir-exception#7]
`.printStackTrace` shows the cause of the exception at the terminal:
![screen shot 2015-04-10 at 17 50 25](https://cloud.githubusercontent.com/assets/2167559/7093304/d7d23e1a-dfaf-11e4-8371-2bc6b3b1f1ce.png)
But that cause isn't included in the `error`/`request` information page:
![screen shot 2015-04-10 at 17 50 02](https://cloud.githubusercontent.com/assets/2167559/7093313/ed90e7e2-dfaf-11e4-8c6b-092fa9008a05.png)
The cause seems quite important. Did you leave it out for some reason?

**Comment by yogthos** [comment]
I would've expected cause to be printed as it goes through the causes [here](https://github.com/yogthos/noir-exception/blob/f95c964cac30bd7961914a2f69d81bb4b4e98811/src/noir_exception/core.clj#L54), so probably a bug in the logic there.

**Comment by ccfontes** [comment]
OK, I will fix that.

**Comment by yogthos** [comment]
:+1:

**Comment by yogthos** [comment]
and I might as well push out a new release with the fix then

**Comment by ccfontes** [comment]
That would be great :)

Could look prettier:
![screen shot 2015-04-11 at 08 15 37](https://cloud.githubusercontent.com/assets/2167559/7100584/ebeb6660-e022-11e4-89fa-2d437f91f4d9.png)

**Comment by ccfontes** [comment]
btw, css class `cause` in:
![screen shot 2015-04-11 at 08 25 05](https://cloud.githubusercontent.com/assets/2167559/7100612/44b3f93c-e024-11e4-9941-228c30724e22.png)
is not defined

**Comment by ccfontes** [comment]
I think it looks better:
![screen shot 2015-04-11 at 08 36 08](https://cloud.githubusercontent.com/assets/2167559/7100651/d044de3e-e025-11e4-9245-9cd2981656a0.png)
Do you prefer other style?

**Comment by yogthos** [comment]
I'm pretty neutral on that, so whichever one you like better sounds good to me

**Comment by ccfontes** [comment]
Could you wait for another PR regarding reuse of the generated html page with `error`/`request` before making the release?

**Comment by yogthos** [comment]
yeah sure thing
